<?php

/**
 * SSO Moodle Module
 * Copyright 2012 Projecte Ictineo (www.projecteictineo.com)
 * GPL v3
 */

/**
 * Implemetns hook_form_alter().
 */
function sso_moodle_form_alter(&$form, $form_state, $form_id) {
  if($form_id == 'user_login' || $form_id == 'user_login_block') {

    // Prepare the <form id= value for working in js size
    if($form_id == 'user_login') {
      $jsformid = 'form#user-login';
    } else {
      $jsformid = 'form#user-login-form';
    }

    $form['#attached'] = 
      array (
        'js' => array(array (
          'type' => 'file',
          'data' => drupal_get_path('module','sso_moodle') . '/js/ajax.js',
        ), array (
          'type' => 'setting',
          'data' => array('sso_moodle' => array (
            'login_url' => variable_get('moodle_login_url',''),
            'form_id' => $jsformid,
            ),
          ),
        ),
      ));
  }
}
/**
* Implements hook_block_info().
*/
function sso_moodle_block_info() {
    $blocks['sso_login'] = array(
        'info' => t('SSO login'), //The name that will appear in the block list.
            'cache' => DRUPAL_CACHE_PER_ROLE, //Default
              );
      return $blocks;
}

function sso_moodle_block_view($delta = '' ) {
  switch($delta) {
    case 'sso_login':
      $block['subject'] = t('Login to moodle');
        $block['content'] = drupal_get_form(sso_moodle_form_login);
  }
  return $block;
}

function sso_moodle_form_login() {
  // Settings to pass into javascript file with the login url
  drupal_add_js(array('sso_moodle' =>array('login_url' =>variable_get('moodle_login_url',''))), 'setting');

  $form['#method'] = 'post';
  $form['#attributes'] = array( 'id' => 'sso-moodle-login-form' );
  $form['#attached'] = array (
    'js' => array (
      'type' => 'file',
      'data' => drupal_get_path('module','sso_moodle') . '/js/ajax.js',
    ),
    'css' => array (
      'type' => 'file',
      'data' => drupal_get_path('module','sso_moodle') . '/css/block.css',
    ),
  );
  $form['description'] = array(
    '#type' => 'item', 
    '#title' => t('Enter your moodle user/passwd'), 
    '#description' => t('Enter your user'),
  );
  $form['username'] = array(
    '#type' => 'textfield', 
    '#title' => t('Username'), 
    '#required' => TRUE, 
  );
  $form['password'] = array(
    '#type' => 'password', 
    '#title' => t('Password'), 
    '#required' => TRUE, 
  );
  $form['log'] = array(
    '#type' => 'button', 
    '#value' => t('Login'),
  );
  return $form;
}

function sso_moodle_moodle_login($form_state, $form) {
}

/**
 * Implementation of hook_menu()
 */
function sso_moodle_menu() {
  $items = array();

  $items['admin/config/content/sso_moodle'] = array(
    'title' => 'SSO to Moodle configuration',
    'description' => 'Configure the SSO to Moodle params',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sso_moodle_config_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function sso_moodle_config_form ($form, &$form_state) {
  $form['moodle_login_url'] = array(
    '#type' => 'textfield',
    '#title' => t('URL to the Moodle login page'),
    '#description' => t('The URL to the Moodle login page, for example, http://example.com/moodle/login/index.php'),
    '#required' => TRUE,
    '#default_value' => variable_get('moodle_login_url', ''), 
  );
  $form['moodle_sso_tigger_login'] = array(
    '#type' => 'select',
    '#title' => t('Tigger the SSO petition on default login form'),
    '#options' => array( 0 => 'No', 1 => 'Yes'),
    '#default_value' => variable_get('moodle_sso_tigger_login', 0),
  ); 

  return system_settings_form($form);
}

